#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
  # Update icon cache
  if [ -x /usr/bin/gtk-update-icon-cache ]; then
    gtk-update-icon-cache -f /usr/share/icons/hicolor
  fi

  # Update desktop database
  if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database /usr/share/applications
  fi
fi
